apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: drupal
          ports:
            - containerPort: 80