apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal
spec:
  rules:
    - host: drupal.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drupal
                port:
                  number: 80
